# Generated by Django 5.1.6 on 2025-03-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blooddonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('bloodgroup', models.TextField(max_length=3)),
                ('donationdate', models.DateField()),
            ],
        ),
    ]
