# Generated by Django 5.1.6 on 2025-03-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanjilahamed_bloodgroup_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='number',
            field=models.IntegerField(max_length=11),
        ),
    ]
